# For Docs:
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin    : contrast # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-twitter-plugin


  
# Site Settings
locale                   : "en-US"
title                    : ""
description              : "Home of the Fred Hutch Data Science Lab"
url                      :  "https://hutchdatascience.org/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  :  # the subpath of your site, e.g. "/blog"
repository               : "fhdsl/fhdsl.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
logo                     : "/images/FHDaSL_SQ-funfetti.png" ## "/images/fhdasl-brothers-squared.png"
teaser                   : #"/images/FHDataScienceLab_Rec.png"  ## "/images/Data-Science-Lab.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"


# atom_feed:
#   hide: true
#   path                   :  # blank (default) uses feed.xml
# search                   :  true #, false (default)
# search_full_content      :  true #, false (default)
# search_provider          :  lunr #(default), algolia, google
# google:
#   search_engine_id       : # YOUR_SEARCH_ENGINE_ID
#   instant_search         : # false (default), true
# # SEO Related
# google_site_verification :

# Social Sharing
twitter:
  username               :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)



# Reading Files
include:
  - _data
  - assets
  - _layouts
  - images
  - _pages
exclude:
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown



# Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      share: true
      layout: single
      classes: wide
      toc: true
      toc_label: "On This Page"
      toc_sticky: true
      header:
        overlay_color: "#123054"
        overlay_filter: "0.2"
        overlay_image: "/images/FHDataScienceLab_brothers.png"
      sidebar:
        nav: "frontpage"
      
#_pages
  # - scope:
  #     path: "_pages"
  #     type: pages
  #   values:
  #     layout: single
  #     share: true
  #     toc: true
  #     toc_label: "On This Page"
  #     toc_sticky: true
  #     sidebar:
  #       nav: "frontpage"


footer:
  links:
    - label: "See our GitHub Org"
      icon: "fab fa-fw fa-github"
      url: https://github.com/fhdsl
    - label: "Join the Conversation on Slack"
      icon: "fab fa-fw fa-slack"
      url: https://fhdata.slack.com/
    - label: "Read Hutch Data Science Docs"
      icon: "fas fa-book"
      url: https://sciwiki.fredhutch.org


# For blog posts:

# Outputting
permalink: /news/:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /news/categories/
tag_archive:
  type: liquid
  path: /news/tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
