---
title: "DaSL Collection"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
favicon: assets/dasl_favicon.ico
description: "A collection of DaSL materials"
always_allow_html: true
output:
    bookdown::html_document2:
      toc: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source("scripts/render_collection.R")
# load libraries ----
install.packages("DT", repos='http://cran.us.r-project.org')
library(DT)
```

# Browse Our Materials

## Courses & Tutorials

```{r, echo = FALSE, message = FALSE, warning = FALSE}
dt <- datatable(
  make_collection_table(include = c("course")),
  #extensions = c("SearchBuilder", "DateTime"),
  escape = FALSE,
  # Make cell values html enabled
  rownames = FALSE,
  # Remove 1, 2, 3 labels
  options = list(
    autowidth = TRUE,
    search = list(regex = TRUE),
    pageLength = 100, # Show 100 results
    dom = 'ft', # Don't allow to change how many results are displayed
    # dom = "Qlfrtip",
    # searchBuilder = TRUE,
    search = list(return = TRUE)
  )
)
dt
```

## EdTech Software

```{r, echo = FALSE, message = FALSE, warning = FALSE}
dt <- datatable(
  make_collection_table(include = c("edtech-software")),
  #extensions = c("SearchBuilder", "DateTime"),
  escape = FALSE,
  # Make cell values html enabled
  rownames = FALSE,
  # Remove 1, 2, 3 labels
  options = list(
    autowidth = TRUE,
    search = list(regex = TRUE),
    pageLength = 100, # Show 100 results
    dom = 'ft', # Don't allow to change how many results are displayed
    # dom = "Qlfrtip",
    # searchBuilder = TRUE,
    search = list(return = TRUE)
  )
)
dt
```

<br><br><br>
This page was last updated on `r Sys.time()`


